// src/components/CustomCursor.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import gsap from 'gsap'

const isHovered = ref(false)
const isVisible = ref(false)
const ringRef = ref(null)

onMounted(() => {
  const canUseCustomCursor = window.matchMedia("(pointer: fine)").matches
  if (!canUseCustomCursor) return

  // GSAP quickTo is perfect for high-performance following elements
  const xTo = gsap.quickTo(ringRef.value, "x", { duration: 0.6, ease: "power3" })
  const yTo = gsap.quickTo(ringRef.value, "y", { duration: 0.6, ease: "power3" })

  const moveMouse = (e) => {
    xTo(e.clientX)
    yTo(e.clientY)
    if (!isVisible.value) isVisible.value = true
  }

  const handleHoverStart = (e) => {
    const target = e.target
    if (
      target.tagName === "BUTTON" ||
      target.tagName === "A" ||
      target.closest("button") ||
      target.closest("a") ||
      target.getAttribute("role") === "button"
    ) {
      isHovered.value = true
    } else {
      isHovered.value = false
    }
  }

  const handleMouseLeave = () => isVisible.value = false
  const handleMouseEnter = () => isVisible.value = true

  window.addEventListener("mousemove", moveMouse)
  window.addEventListener("mouseover", handleHoverStart)
  document.addEventListener("mouseleave", handleMouseLeave)
  document.addEventListener("mouseenter", handleMouseEnter)

  onUnmounted(() => {
    window.removeEventListener("mousemove", moveMouse)
    window.removeEventListener("mouseover", handleHoverStart)
    document.removeEventListener("mouseleave", handleMouseLeave)
    document.removeEventListener("mouseenter", handleMouseEnter)
  })
})
</script>

<template>
  <div v-show="isVisible" class="fixed inset-0 pointer-events-none z-[9999]">
    <div
      ref="ringRef"
      class="fixed left-0 top-0 rounded-full border-2 border-white/40 z-0 bg-white/5 backdrop-blur-[2px] transition-all duration-300 pointer-events-none"
      :style="{
        transform: 'translate(-50%, -50%)',
        opacity: isHovered ? 1 : 0,
        width: isHovered ? '54px' : '27px',
        height: isHovered ? '54px' : '27px',
      }"
    />
  </div>
</template>

// src/components/custom-cursor.tsx
"use client";

import React, { useEffect, useState } from "react";
import { motion, useSpring, useMotionValue } from "framer-motion";

export function CustomCursor() {
  const [isHovered, setIsHovered] = useState(false);
  const [isVisible, setIsVisible] = useState(false);

  // Motion values for smooth tracking
  const cursorX = useMotionValue(-100);
  const cursorY = useMotionValue(-100);

  // Spring settings for the larger outer ring (trailing effect)
  const springConfig = { damping: 20, stiffness: 150, mass: 0.5 };
  const ringX = useSpring(cursorX, springConfig);
  const ringY = useSpring(cursorY, springConfig);

  useEffect(() => {
    // Check if device has a fine pointer (desktop)
    const canUseCustomCursor = window.matchMedia("(pointer: fine)").matches;
    if (!canUseCustomCursor) return;

    const moveMouse = (e: MouseEvent) => {
      cursorX.set(e.clientX);
      cursorY.set(e.clientY);
      if (!isVisible) setIsVisible(true);
    };

    const handleHoverStart = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (
        target.tagName === "BUTTON" ||
        target.tagName === "A" ||
        target.closest("button") ||
        target.closest("a") ||
        target.getAttribute("role") === "button"
      ) {
        setIsHovered(true);
      } else {
        setIsHovered(false);
      }
    };

    const handleMouseLeave = () => setIsVisible(false);
    const handleMouseEnter = () => setIsVisible(true);

    window.addEventListener("mousemove", moveMouse);
    window.addEventListener("mouseover", handleHoverStart);
    document.addEventListener("mouseleave", handleMouseLeave);
    document.addEventListener("mouseenter", handleMouseEnter);

    return () => {
      window.removeEventListener("mousemove", moveMouse);
      window.removeEventListener("mouseover", handleHoverStart);
      document.removeEventListener("mouseleave", handleMouseLeave);
      document.removeEventListener("mouseenter", handleMouseEnter);
    };
  }, [cursorX, cursorY, isVisible]);

  if (!isVisible) return null;

  return (
    <div className="fixed inset-0 pointer-events-none z-[9999]">
      {/* Trailing Ring - Surfaces around the 'hand' cursor on hover */}
      <motion.div
        className="fixed rounded-full border-2 border-white/40 z-0 bg-white/5 backdrop-blur-[2px]"
        initial={{ opacity: 0, scale: 0.5 }}
        style={{
          x: ringX,
          y: ringY,
          translateX: "-50%",
          translateY: "-50%",
        }}
        animate={{
          opacity: isHovered ? 1 : 0,
          scale: isHovered ? 1 : 0.5,
          width: 54,
          height: 54,
        }}
        transition={{ 
          opacity: { duration: 0.2 },
          scale: { type: "spring", damping: 25, stiffness: 200 },
          default: { type: "spring", damping: 20, stiffness: 150, mass: 0.5 }
        }}
      />
    </div>
  );
}
